name: Build and Test Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t my-static-site .

      # Optional: Run the container to check if it starts properly
      - name: Run Container (for testing)
        run: |
          docker run -d -p 8080:80 --name test-site my-static-site
          sleep 5
          docker ps
